services:
  # backend
  backend:
    build:
      context: ./task-tracker-backend
      dockerfile: Dockerfile
    image: task-tracker-backend:latest
    container_name: task-tracker-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db
    restart: unless-stopped

  # postgres
  db:
    image:    postgres:18
    restart:  unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_NAME:      ${POSTGRES_NAME}
      POSTGRES_USERNAME:  ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  adminer:
    image: adminer:5
    restart: unless-stopped
    ports:
      - "5050:8080"
    depends_on:
      - db


volumes:
  pgdata:
